name: Create Preview Builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build Android Preview
    type: build
    params:
      platform: android
      profile: preview-android

  build_ios:
    name: Build iOS Preview
    type: build
    params:
      platform: ios
      profile: preview-ios
