name: Create Production Builds

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build Android Production
    type: build
    params:
      platform: android
      profile: production-android

  # build_ios:
  #   name: Build iOS Production
  #   type: build
  #   params:
  #     platform: ios
  #     profile: production-ios
